const express=require('express');
const Database=require('better-sqlite3');
const fs=require('fs');
const path=require('path');
const app=express();
const PORT=process.env.PORT||3000;
app.use(express.json({limit:'100kb'}));
app.use(express.static(path.join(__dirname,'public')));
const dir=path.join(__dirname,'database'); fs.mkdirSync(dir,{recursive:true});
const db=new Database(path.join(dir,'reflex.db')); db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS riders(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,fleet_no TEXT UNIQUE NOT NULL,plate_no TEXT UNIQUE NOT NULL,availability TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK(availability IN ('AVAILABLE','BUSY')));
CREATE TABLE IF NOT EXISTS deliveries(id INTEGER PRIMARY KEY AUTOINCREMENT,delivery_code TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,customer_phone TEXT NOT NULL,customer_email TEXT,address TEXT NOT NULL,item_description TEXT NOT NULL,barcode TEXT NOT NULL,payment_method TEXT,status TEXT NOT NULL DEFAULT 'CREATED' CHECK(status IN ('CREATED','ASSIGNED','PICKED_UP','DELIVERED')),created_at TEXT NOT NULL,otp_code TEXT,otp_verified INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,delivery_id INTEGER NOT NULL UNIQUE,rider_id INTEGER NOT NULL,assigned_at TEXT NOT NULL,FOREIGN KEY(delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE,FOREIGN KEY(rider_id) REFERENCES riders(id));`);
if (db.prepare('SELECT COUNT(*) c FROM riders').get().c === 0) {
  const seed = db.transaction(() => {
    const insert = db.prepare(
      'INSERT INTO riders (name, phone, fleet_no, plate_no) VALUES (?, ?, ?, ?)'
    );

    insert.run('John Kamau', '0712345678', 'FL-017', 'KDA 123A');
    insert.run('Mary Wanjiku', '0723456789', 'FL-023', 'KDB 456B');
  });

  seed();
}

const now=()=>new Date().toISOString(); const valid=n=>Number.isInteger(n)&&n>0;
function delivery(id){return db.prepare(`SELECT d.*,a.rider_id,r.name rider_name,r.phone rider_phone,r.fleet_no rider_fleet_no,r.plate_no rider_plate_no,r.availability rider_availability FROM deliveries d LEFT JOIN assignments a ON a.delivery_id=d.id LEFT JOIN riders r ON r.id=a.rider_id WHERE d.id=?`).get(id)}
function riderFor(id){return db.prepare('SELECT r.* FROM assignments a JOIN riders r ON r.id=a.rider_id WHERE a.delivery_id=?').get(id)}
app.get('/api/health',(q,s)=>s.json({status:'ok',service:'Reflex'}));
app.get('/api/deliveries',(q,s)=>s.json(db.prepare(`SELECT d.*,a.rider_id,r.name rider_name,r.phone rider_phone,r.fleet_no rider_fleet_no,r.plate_no rider_plate_no,r.availability rider_availability FROM deliveries d LEFT JOIN assignments a ON a.delivery_id=d.id LEFT JOIN riders r ON r.id=a.rider_id ORDER BY d.id DESC`).all()));
app.get('/api/riders',(q,s)=>s.json(db.prepare('SELECT * FROM riders ORDER BY id').all()));
app.get('/api/riders/:id/deliveries',(q,s)=>{const id=Number(q.params.id);if(!valid(id))return s.status(400).json({error:'Valid rider ID is required'});if(!db.prepare('SELECT id FROM riders WHERE id=?').get(id))return s.status(404).json({error:'Rider not found'});s.json(db.prepare(`SELECT d.*,a.rider_id,a.assigned_at FROM deliveries d JOIN assignments a ON a.delivery_id=d.id WHERE a.rider_id=? ORDER BY d.id DESC`).all(id))});
app.post('/api/deliveries',(q,s)=>{const b=q.body||{};const req=['customerName','customerPhone','address','itemDescription','barcode'];if(req.some(k=>typeof b[k]!=='string'||!b[k].trim()))return s.status(400).json({error:'Customer name, phone, address, item description and barcode are required'});const last=db.prepare('SELECT id FROM deliveries ORDER BY id DESC LIMIT 1').get();const code='DEL-'+String((last?.id||0)+1).padStart(6,'0');try{const r=db.prepare(`INSERT INTO deliveries(delivery_code,customer_name,customer_phone,customer_email,address,item_description,barcode,payment_method,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(code,b.customerName.trim(),b.customerPhone.trim(),String(b.customerEmail||'').trim(),b.address.trim(),b.itemDescription.trim(),b.barcode.trim(),String(b.paymentMethod||'').trim(),now());s.status(201).json({message:'Delivery created successfully',delivery:delivery(r.lastInsertRowid)})}catch(e){console.error(e);s.status(500).json({error:'Unable to create delivery'})}});
function assign(did,rid){const d=db.prepare('SELECT * FROM deliveries WHERE id=?').get(did);if(!d)throw Object.assign(new Error('Delivery not found'),{status:404});if(d.status!=='CREATED')throw Object.assign(new Error('Only CREATED deliveries can be assigned'),{status:409});const r=db.prepare('SELECT * FROM riders WHERE id=?').get(rid);if(!r)throw Object.assign(new Error('Rider not found'),{status:404});if(r.availability!=='AVAILABLE')throw Object.assign(new Error('Rider is not available'),{status:409});if(db.prepare('SELECT id FROM assignments WHERE delivery_id=?').get(did))throw Object.assign(new Error('Delivery is already assigned'),{status:409});db.transaction(()=>{db.prepare('INSERT INTO assignments(delivery_id,rider_id,assigned_at) VALUES(?,?,?)').run(did,rid,now());db.prepare("UPDATE deliveries SET status='ASSIGNED' WHERE id=?").run(did);db.prepare("UPDATE riders SET availability='BUSY' WHERE id=?").run(rid)})()}
function assignmentRoute(req,res){const did=Number(req.params.id||req.body?.deliveryId),rid=Number(req.body?.riderId);if(!valid(did)||!valid(rid))return res.status(400).json({error:'Valid delivery ID and rider ID are required'});try{assign(did,rid);res.json({message:'Rider assigned successfully',delivery:delivery(did)})}catch(e){console.error(e);res.status(e.status||500).json({error:e.status?e.message:'Unable to assign rider'})}}
app.post('/api/assignments',assignmentRoute);app.post('/api/deliveries/:id/assign',assignmentRoute);
app.post('/api/deliveries/:id/scan',(q,s)=>{const did=Number(q.params.id),rid=Number(q.body?.riderId),barcode=typeof q.body?.barcode==='string'?q.body.barcode.trim():'';if(!valid(did)||!valid(rid)||!barcode)return s.status(400).json({error:'Valid delivery ID, rider ID and barcode are required'});const d=db.prepare('SELECT * FROM deliveries WHERE id=?').get(did);if(!d)return s.status(404).json({error:'Delivery not found'});if(d.status!=='ASSIGNED')return s.status(409).json({error:'Barcode pickup verification is only allowed for ASSIGNED deliveries'});const r=riderFor(did);if(!r)return s.status(409).json({error:'No rider is assigned to this delivery'});if(r.id!==rid)return s.status(403).json({error:'You are not the rider assigned to this delivery'});if(barcode!==d.barcode)return s.status(409).json({error:'Barcode mismatch'});db.prepare("UPDATE deliveries SET status='PICKED_UP' WHERE id=?").run(did);s.json({message:'Barcode verified and pickup confirmed',deliveryId:did,status:'PICKED_UP'})});
app.post('/api/deliveries/:id/generate-otp',(q,s)=>{const id=Number(q.params.id);if(!valid(id))return s.status(400).json({error:'Valid delivery ID is required'});const d=db.prepare('SELECT * FROM deliveries WHERE id=?').get(id);if(!d)return s.status(404).json({error:'Delivery not found'});if(d.status!=='PICKED_UP')return s.status(409).json({error:'OTP can only be generated for a picked-up delivery'});const otp=String(Math.floor(100000+Math.random()*900000));db.prepare('UPDATE deliveries SET otp_code=?,otp_verified=0 WHERE id=?').run(otp,id);s.json({message:'OTP generated successfully',deliveryId:id,otp})});
app.post('/api/deliveries/:id/verify-otp',(q,s)=>{const id=Number(q.params.id),otp=String(q.body?.otp??'').trim();if(!valid(id)||!/^[0-9]{6}$/.test(otp))return s.status(400).json({error:'Valid delivery ID and six-digit OTP are required'});const d=db.prepare('SELECT * FROM deliveries WHERE id=?').get(id);if(!d)return s.status(404).json({error:'Delivery not found'});if(d.status!=='PICKED_UP')return s.status(409).json({error:'Only picked-up deliveries can be completed'});if(!d.otp_code)return s.status(409).json({error:'Recipient OTP has not been generated'});if(otp!==d.otp_code)return s.status(409).json({error:'Invalid recipient OTP'});const r=riderFor(id);db.transaction(()=>{db.prepare("UPDATE deliveries SET status='DELIVERED',otp_verified=1 WHERE id=?").run(id);if(r)db.prepare("UPDATE riders SET availability='AVAILABLE' WHERE id=?").run(r.id)})();s.json({message:'Delivery confirmed successfully',deliveryId:id,status:'DELIVERED'})});
app.use((req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'API endpoint not found'}):res.status(404).send('Page not found'));
app.use((e,req,res,next)=>{if(e instanceof SyntaxError&&e.status===400&&'body' in e)return res.status(400).json({error:'Invalid JSON request body'});console.error(e);res.status(500).json({error:'Internal server error'})});
app.listen(PORT,'0.0.0.0',()=>console.log(`Reflex server is running on port ${PORT}`));
